app/game/forms.py
from flask_wtf import FlaskForm                                                             # type:ignore
from wtforms import StringField, SubmitField, SelectField, IntegerField, HiddenField        # type:ignore
from wtforms.validators import DataRequired                                                 # type:ignore 
from flask_login import current_user                                                        # type:ignore                                             # type:ignore
from app.models import Game 


## Game Setup related Forms
class NewGameForm(FlaskForm):
    game_name = StringField('Game Name', validators=[DataRequired()])
    newgame_button = SubmitField('Create Game')

class LoadGameForm(FlaskForm):
    game_id = SelectField('Select Game', coerce=int)
    loadgame_button = SubmitField('Load Game')

    def __init__(self, *args, **kwargs):
        super(LoadGameForm, self).__init__(*args, **kwargs)
        self.game_id.choices = [(game.id, game.game_name) for game in Game.query.filter_by(user_id=current_user.id).all()][::-1]


## Game Play related Forms
class AddXPForm(FlaskForm):
    xp = IntegerField('XP', validators=[DataRequired()])
    addxp_button = SubmitField('Add XP')

class AddCashForm(FlaskForm):
    cash = IntegerField('Cash', validators=[DataRequired()])
    addcash_button = SubmitField('Add Cash')

class AddResourcesForm(FlaskForm):
    xp = IntegerField('XP')
    cash = IntegerField('Cash')
    wood = IntegerField('Wood')
    stone = IntegerField('Stone')
    metal = IntegerField('Iron')
    add_button = SubmitField('Add Resources')

class CollectResourcesForm(FlaskForm):
    collect_button = SubmitField('Collect Resources')
    

class UpgradeBuildingForm(FlaskForm):
    upgrade_button = SubmitField('Upgrade')

class CompleteQuestForm(FlaskForm):
    quest_id = HiddenField('Quest ID')
    complete_button = SubmitField('Complete Quest')

app/game/__init__.py
from flask import Blueprint
from app.game.context_processor import load_game

bp = Blueprint('game', __name__)

@bp.before_app_request
def before_request():
    load_game()

from app.game import routes

app/game/routes.py
from flask import render_template, redirect, url_for, flash, request, g
from flask_login import login_required, current_user            # type:ignore

from app.game.forms import NewGameForm, LoadGameForm, AddResourcesForm, CollectResourcesForm, UpgradeBuildingForm, CompleteQuestForm
from app.game.game_services import GameService, GameCreation
from app.game.buildings.building_services import GameBuildingService
from app.game.quests.quest_services import QuestService, QuestManager
from app.game import bp
from app.models import db, Game
from app.models import InventoryUser
from app.models import QuestProgress
from app.models import BuildingProgress
from app.models import HeroProgress


@bp.route('/startmenu', methods=['GET', 'POST'])
@login_required
def startmenu():

    newgameform = NewGameForm()
    loadgameform = LoadGameForm()

    numberofgames = Game.query.filter_by(user_id=current_user.id).count()
       
    if request.method == 'POST' and newgameform.newgame_button.data:
        
        game_name = newgameform.game_name.data
        
        service = GameCreation(user_id=current_user.id, game_name=game_name)
        game = service.create_game()
        
        service.create_all_startup(game.id)
        db.session.commit()
        
        game_id = game.id
        
    
        return redirect(url_for('game.play', 
                                game_id=game_id))
    
    if request.method == 'POST' and loadgameform.loadgame_button.data:
        game_id = loadgameform.game_id.data
        current_user.activegame = game_id
        db.session.commit()
        return redirect(url_for('game.play', 
                                game_id=game_id))


    return render_template("game/startmenu.html", 
                           title='Start Menu', 
                           newgameform=newgameform,
                           loadgameform=loadgameform,
                           numberofgames=numberofgames)


## Route to display game play
@bp.route('/play/<game_id>', methods=['GET', 'POST'])
@login_required
def play(game_id):
    # validate user
    if not current_user.is_admin() and current_user.activegame != int(game_id):
        return redirect(url_for('admin.not_admin'))

    game = g.game  # Optimized query
    if not game:
        flash('Game not found.', 'error')
        return redirect(url_for('main.index'))

    resourceform = AddResourcesForm()
    service = GameService(game_id=game_id)

    if request.method == 'POST' and resourceform.add_button.data:
        service.update_resources(xp=resourceform.xp.data,
                                    cash=resourceform.cash.data,
                                    wood=resourceform.wood.data,
                                    stone=resourceform.stone.data,
                                    metal=resourceform.metal.data,
                                    source="Manual Resource Form")
        flash('Resources Added')
        
        # Quest Manager
        questmanager = QuestManager(game_id=game.id)
        questmanager.update_quests()
        
        return redirect(url_for('game.play', game_id=game_id))

    return render_template("game/play.html", game=game, resourceform=resourceform)
    


# Route to display quests
@bp.route('/building_quests/<building_progress_id>', methods=['GET', 'POST'])
@login_required
def building_quests(building_progress_id):
    
       
    building_progress = BuildingProgress.query.get(building_progress_id)
    if not building_progress:
        flash('Building progress not found.', 'error')
        return redirect(url_for('main.index'))
    
    # Check if current user is admin or the current user viewing their own profile
    if not current_user.is_admin() and current_user.activegame != int(building_progress.game_id):
        return redirect(url_for('admin.not_admin'))
    
    game = g.game  # Optimized query
    if not game:
        flash('Game not found.', 'error')
        return redirect(url_for('main.index'))

    if not current_user.is_admin() and current_user.activegame != int(game.id):
        return redirect(url_for('admin.not_admin'))
   
    
    # Forms
    completequestform = CompleteQuestForm(request.form)
    
    quests = QuestProgress.query.filter_by(game_id=game.id).all()
    # Categorize quests in Python to reduce database load
    active_quests = [q for q in quests if q.quest_active and not q.quest_completed]
    completed_quests = [q for q in quests if q.quest_completed]
    inactive_quests = [q for q in quests if not q.quest_active and not q.quest_completed]

    if request.method == 'POST' and completequestform.validate_on_submit():
        quest_id = completequestform.quest_id.data
        service = QuestService(quest_progress_id=quest_id)
        service.complete_quest()
        db.session.commit()
        return redirect(url_for('game.building_quests', building_progress_id=building_progress_id))

    return render_template("game/buildings/building_quests.html", 
                           title='Quests',
                           game=game,
                           quests=quests,
                           active_quests=active_quests,
                           completed_quests=completed_quests,
                           inactive_quests=inactive_quests,
                           completequestform=completequestform)

# Route to display inventory
@bp.route('/building_inventory/<game_id>', methods=['GET', 'POST'])
@login_required
def building_inventory(game_id):
    # Query for game inventory items
    game = g.game  # Optimized query
    userinventories = InventoryUser.query.filter_by(game_id=game_id).all()
    
    return render_template("game/buildings/building_inventory.html",
                           title='Inventory',
                            game=game,
                            userinventories=userinventories)


# Route to display resource buildings
@bp.route('/building_resource/<building_progress_id>', methods=['GET', 'POST'])
@login_required
def building_resource(building_progress_id):
    
    # Query for game inventory items
    building_progress = BuildingProgress.query.filter_by(id=building_progress_id).first()
    game = g.game  # Optimized query
    
    if not current_user.is_admin() and current_user.activegame != int(game.id):
        return redirect(url_for('admin.not_admin'))
    


    # Forms
    collectresourcesform = CollectResourcesForm()
    upgradebuildingform = UpgradeBuildingForm()

    # calculate accrued resources:
    buildingservice = GameBuildingService(building_progress_id=building_progress_id)
    buildingservice.calculate_accrued_resources()


    # Calculate required resources
    required_resources = buildingservice._calculate_required_resources()

    # Handle POST requests
    if request.method == 'POST' and collectresourcesform.collect_button.data:
        buildingservice.collect_resources()
        
        return redirect(url_for('game.building_resource', building_progress_id=building_progress_id))

    if request.method == 'POST' and upgradebuildingform.upgrade_button.data:
        buildingservice.upgrade_building()

        return redirect(url_for('game.building_resource', building_progress_id=building_progress_id))


    return render_template("game/buildings/building_resource.html",
                           title=building_progress.building.building_name,
                            game=game,
                            building_progress=building_progress,
                            buildingservice=buildingservice,
                            collectresourcesform=collectresourcesform,
                            upgradebuildingform=upgradebuildingform,
                            required_resources=required_resources)


# Route to display barracks building
@bp.route('/building_barracks/<building_progress_id>', methods=['GET', 'POST'])
@login_required
def building_barracks(building_progress_id):

    building_progress = BuildingProgress.query.filter_by(id=building_progress_id).first()
    game = g.game

    heroes = HeroProgress.query.filter_by(game_id=game.id).all()
    
    return render_template("game/buildings/building_barracks.html",
                            title='Barracks',
                            game=game,
                            building_progress=building_progress,
                            heroes=heroes)



@bp.route('/hero/<hero_progress_id>', methods=['GET','POST'])
@login_required
def hero(hero_progress_id):
    hero_progress = HeroProgress.query.filter_by(id=hero_progress_id).first()
    game = g.game

    return render_template("game/hero.html",
                           title=f"Hero: {hero_progress.hero.hero_name}",
                           hero_progress=hero_progress,
                           game=game)
    
@bp.route('/building_campaign/<building_progress_id>', methods=['GET','POST'])
@login_required
def building_campaign(building_progress_id):
    
    building_progress = BuildingProgress.query.filter_by(id=building_progress_id).first()
    game=g.game
    
    return render_template("game/buildings/building_campaign.html",
                           title="Campaign",
                           game=game,
                           building_progress=building_progress)
    
    
@bp.route('/battle', methods=['GET','POST'])
@login_required
def battle():
    
    game=g.game
    
    return render_template("game/battle.html",
                           title="Campaign",
                           game=game)

app/templates/game/battle.html
{% extends "game/game_base.html" %}

{% block content2 %}

<div>
    <p><b>Player 1:</b></p>

    <p>Hero1</p>
    <p>Hero2</p>
    <p>Hero3</p>
    <p>Hero4</p>

</div>




<div>
    <p><b>Player 2:</b></p>
    <p>Hero1</p>
    <p>Hero2</p>
    <p>Hero3</p>
    <p>Hero4</p>
</div>


{% endblock content2 %}

app/templates/game/game_base.html
{% extends "base.html" %}

{% block content %}

<script>
    var loc = window.location;
    var wsStart = loc.protocol === "https:" ? "wss://" : "ws://";
    var wsUrl = wsStart + loc.host + "/ws";
    var socket = new WebSocket(wsUrl);

    socket.onopen = function(event) {
        console.log('WebSocket is open now.');
    };

    socket.onclose = function(event) {
        console.log('WebSocket is closed now.');
    };

    socket.onerror = function(error) {
        console.log('WebSocket error: ' + error);
    };
</script>

<h1>  {{ game.user.username }} - {{ game.game_name }} - {{ title }}  </h1>

<hr>

<div style="display: flex; justify-content: space-around;">

    <p>XP: {{ game.xp }}/{{game.next_level_xp_required}}</p>
    <p>Level: {{ game.level}}</p>
    <p>Cash: {{ game.cash }}</p>
    <p>Wood: {{ game.wood }}</p>
    <p>Stone: {{ game.stone }}</p>
    <p>Metal: {{ game.metal }}</p>

</div>

<hr>

<!-- Link for Quests -->
<div style="display: flex; justify-content: space-around;">

    <a href="{{ url_for('game.play', game_id=game.id) }}">Home</a> - 

    <!--return link for the quest building related to the game-->
    {% for building in game.building_progress %}
       {% if building.building.id == 1 %}
            <a href="{{ url_for('game.building_quests', building_progress_id=building.id) }}">Quest</a> - 
       {% endif %}
    {% endfor %}

    <a href="{{ url_for('game.building_inventory', game_id=game.id) }}"> Inventory </a>

</div>  

<!-- TODO: Section for Quest Information -->


<hr>

{% block content2 %}  {% endblock content2 %}

{% endblock content %}

app/templates/game/hero.html
{% extends "game/game_base.html" %}

{% block content2 %}


<div class="container text-center">
    <div class="row align-items-start">

      <div class="col">
        <h2>HERO IMAGE BELOW</h2>
        <p> Hero Image</p>
      </div>

      <div class="col">
        <h2>Hero Information:</h2>
        <p>{{hero_progress.hero.hero_description}}</p>
      </div>

      <div class="col">
        <h2>Hero Stats</h2>
        <p>Attack: {{hero_progress.hero_attack}}</p>
      </div>
    </div>
  </div>

{% endblock content2 %}

app/templates/game/play.html
{% extends "game/game_base.html" %}

{% block content2 %}

<div class="container mt-3">
    <div class="row">
        {% for building in game.building_progress %}
        <div class="col-md-4 mb-4">
            <!-- Wrap the card with an <a> tag -->
            {% if building.building.building_type.id == 2 %}
                <a href="{{  url_for(building.building.building_link, game_id=game.id) }}" class="card-link">
            {% else %}
                <a href="{{  url_for(building.building.building_link, building_progress_id=building.id) }}" class="card-link">    
            {% endif %}

                {% if building.building_active %}
                    <div class="card building-active">
                {% else %}
                    <div class="card building-inactive">
                {% endif %}
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ building.building.building_name }}</h5>
                        <p class="card-text">{{ building.building.building_description }}</p>
                        <p class="card-text">Level: {{ building.building_level }}</p>
                    </div>
                </div>
            </a>
        </div>
        {% if loop.index % 3 == 0 %}
    </div><div class="row">
        {% endif %}
        {% endfor %}
    </div>
</div>


<!--FOR TESTING PURPOSES-->
<div>
    <form action="" method="post">
        {{ resourceform.hidden_tag() }}
        <p>{{ resourceform.xp.label }} - {{ resourceform.xp }}</p>
        <p>{{ resourceform.cash.label }} - {{ resourceform.cash }}</p>
        <p>{{ resourceform.wood.label }} - {{ resourceform.wood }}</p>
        <p>{{ resourceform.stone.label }} - {{ resourceform.stone }}</p>
        <p>{{ resourceform.metal.label }} - {{ resourceform.metal }}</p>
        <p>{{ resourceform.add_button() }}</p>
    </form>
</div>

{% endblock content2 %}

app/templates/game/startmenu.html
{% extends "game/game_base.html" %}

{% block content %}

<h1> {{ title }} </h1>

<hr>

{% if numberofgames == 0 %}
    <p>No games found.</p>
{% else %}
    <div>
        <form action="" method="post" novalidate>
            {{ loadgameform.hidden_tag() }}

            <p>
                {{ loadgameform.game_id.label }}<br>
                {{ loadgameform.game_id(class="form-control") }}
                {% for error in loadgameform.game_id.errors %}
                <span style="color: red;">[{{ error }}]</span>
                {% endfor %}
            </p>

            <p>{{ loadgameform.loadgame_button() }}</p>
        </form>
    </div>
{% endif %}

<div>
    <form action="" method="post" novalidate>
        {{ newgameform.hidden_tag() }}
            
            {{ newgameform.game_name.label }}<br>
            {{ newgameform.game_name(class="form-control") }}
            {% for error in newgameform.game_name.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

        <p>{{ newgameform.newgame_button() }}</p>
    </form>
</div>





{% endblock %}