app/game/forms.py
from flask_wtf import FlaskForm                                                             # type:ignore
from wtforms import StringField, SubmitField, SelectField, IntegerField, HiddenField        # type:ignore
from wtforms.validators import DataRequired                                                 # type:ignore 
from flask_login import current_user                                                        # type:ignore                                             # type:ignore
from app.models import Game 


## Game Setup related Forms
class NewGameForm(FlaskForm):
    game_name = StringField('Game Name', validators=[DataRequired()])
    newgame_button = SubmitField('Create Game')

class LoadGameForm(FlaskForm):
    game_id = SelectField('Select Game', coerce=int)
    loadgame_button = SubmitField('Load Game')

    def __init__(self, *args, **kwargs):
        super(LoadGameForm, self).__init__(*args, **kwargs)
        self.game_id.choices = [(game.id, game.game_name) for game in Game.query.filter_by(user_id=current_user.id).all()][::-1]


## Game Play related Forms
class AddXPForm(FlaskForm):
    xp = IntegerField('XP', validators=[DataRequired()])
    addxp_button = SubmitField('Add XP')

class AddCashForm(FlaskForm):
    cash = IntegerField('Cash', validators=[DataRequired()])
    addcash_button = SubmitField('Add Cash')

class AddResourcesForm(FlaskForm):
    xp = IntegerField('XP')
    cash = IntegerField('Cash')
    wood = IntegerField('Wood')
    stone = IntegerField('Stone')
    metal = IntegerField('Iron')
    add_button = SubmitField('Add Resources')

class CollectResourcesForm(FlaskForm):
    collect_button = SubmitField('Collect Resources')
    

class UpgradeBuildingForm(FlaskForm):
    upgrade_button = SubmitField('Upgrade')

class CompleteQuestForm(FlaskForm):
    quest_id = HiddenField('Quest ID')
    complete_button = SubmitField('Complete Quest')

app/game/__init__.py
from flask import Blueprint
from app.game.context_processor import load_game

bp = Blueprint('game', __name__)

@bp.before_app_request
def before_request():
    load_game()

from app.game import routes

app/game/routes.py
from flask import render_template, redirect, url_for, flash, request, g
from flask_login import login_required, current_user            # type:ignore

from app.game.forms import NewGameForm, LoadGameForm, AddResourcesForm, CollectResourcesForm, UpgradeBuildingForm, CompleteQuestForm
from app.game.game_services import GameService, GameCreation
from app.game.buildings.building_services import GameBuildingService
from app.game.quests.quest_services import QuestService, QuestManager
from app.game import bp
from app.models import db, Game
from app.models import InventoryUser
from app.models import QuestProgress
from app.models import BuildingProgress
from app.models import HeroProgress


@bp.route('/startmenu', methods=['GET', 'POST'])
@login_required
def startmenu():

    newgameform = NewGameForm()
    loadgameform = LoadGameForm()

    numberofgames = Game.query.filter_by(user_id=current_user.id).count()
       
    if request.method == 'POST' and newgameform.newgame_button.data:
        
        game_name = newgameform.game_name.data
        
        service = GameCreation(user_id=current_user.id, game_name=game_name)
        game = service.create_game()
        
        service.create_all_startup(game.id)
        db.session.commit()
        
        game_id = game.id
        
    
        return redirect(url_for('game.play', 
                                game_id=game_id))
    
    if request.method == 'POST' and loadgameform.loadgame_button.data:
        game_id = loadgameform.game_id.data
        current_user.activegame = game_id
        db.session.commit()
        return redirect(url_for('game.play', 
                                game_id=game_id))


    return render_template("game/startmenu.html", 
                           title='Start Menu', 
                           newgameform=newgameform,
                           loadgameform=loadgameform,
                           numberofgames=numberofgames)


## Route to display game play
@bp.route('/play/<game_id>', methods=['GET', 'POST'])
@login_required
def play(game_id):
    # validate user
    if not current_user.is_admin() and current_user.activegame != int(game_id):
        return redirect(url_for('admin.not_admin'))

    game = g.game  # Optimized query
    if not game:
        flash('Game not found.', 'error')
        return redirect(url_for('main.index'))

    resourceform = AddResourcesForm()
    service = GameService(game_id=game_id)

    if request.method == 'POST' and resourceform.add_button.data:
        service.update_resources(xp=resourceform.xp.data,
                                    cash=resourceform.cash.data,
                                    wood=resourceform.wood.data,
                                    stone=resourceform.stone.data,
                                    metal=resourceform.metal.data,
                                    source="Manual Resource Form")
        flash('Resources Added')
        
        # Quest Manager
        questmanager = QuestManager(game_id=game.id)
        questmanager.update_quests()
        
        return redirect(url_for('game.play', game_id=game_id))

    return render_template("game/play.html", game=game, resourceform=resourceform)
    


# Route to display quests
@bp.route('/building_quests/<building_progress_id>', methods=['GET', 'POST'])
@login_required
def building_quests(building_progress_id):
    
       
    building_progress = BuildingProgress.query.get(building_progress_id)
    if not building_progress:
        flash('Building progress not found.', 'error')
        return redirect(url_for('main.index'))
    
    # Check if current user is admin or the current user viewing their own profile
    if not current_user.is_admin() and current_user.activegame != int(building_progress.game_id):
        return redirect(url_for('admin.not_admin'))
    
    game = g.game  # Optimized query
    if not game:
        flash('Game not found.', 'error')
        return redirect(url_for('main.index'))

    if not current_user.is_admin() and current_user.activegame != int(game.id):
        return redirect(url_for('admin.not_admin'))
   
    
    # Forms
    completequestform = CompleteQuestForm(request.form)
    
    quests = QuestProgress.query.filter_by(game_id=game.id).all()
    # Categorize quests in Python to reduce database load
    active_quests = [q for q in quests if q.quest_active and not q.quest_completed]
    completed_quests = [q for q in quests if q.quest_completed]
    inactive_quests = [q for q in quests if not q.quest_active and not q.quest_completed]

    if request.method == 'POST' and completequestform.validate_on_submit():
        quest_id = completequestform.quest_id.data
        service = QuestService(quest_progress_id=quest_id)
        service.complete_quest()
        db.session.commit()
        return redirect(url_for('game.building_quests', building_progress_id=building_progress_id))

    return render_template("game/buildings/building_quests.html", 
                           title='Quests',
                           game=game,
                           quests=quests,
                           active_quests=active_quests,
                           completed_quests=completed_quests,
                           inactive_quests=inactive_quests,
                           completequestform=completequestform)

# Route to display inventory
@bp.route('/building_inventory/<game_id>', methods=['GET', 'POST'])
@login_required
def building_inventory(game_id):
    # Query for game inventory items
    game = g.game  # Optimized query
    userinventories = InventoryUser.query.filter_by(game_id=game_id).all()
    
    return render_template("game/buildings/building_inventory.html",
                           title='Inventory',
                            game=game,
                            userinventories=userinventories)


# Route to display resource buildings
@bp.route('/building_resource/<building_progress_id>', methods=['GET', 'POST'])
@login_required
def building_resource(building_progress_id):
    
    # Query for game inventory items
    building_progress = BuildingProgress.query.filter_by(id=building_progress_id).first()
    game = g.game  # Optimized query
    
    if not current_user.is_admin() and current_user.activegame != int(game.id):
        return redirect(url_for('admin.not_admin'))
    


    # Forms
    collectresourcesform = CollectResourcesForm()
    upgradebuildingform = UpgradeBuildingForm()

    # calculate accrued resources:
    buildingservice = GameBuildingService(building_progress_id=building_progress_id)
    buildingservice.calculate_accrued_resources()


    # Calculate required resources
    required_resources = buildingservice._calculate_required_resources()

    # Handle POST requests
    if request.method == 'POST' and collectresourcesform.collect_button.data:
        buildingservice.collect_resources()
        
        return redirect(url_for('game.building_resource', building_progress_id=building_progress_id))

    if request.method == 'POST' and upgradebuildingform.upgrade_button.data:
        buildingservice.upgrade_building()

        return redirect(url_for('game.building_resource', building_progress_id=building_progress_id))


    return render_template("game/buildings/building_resource.html",
                           title=building_progress.building.building_name,
                            game=game,
                            building_progress=building_progress,
                            buildingservice=buildingservice,
                            collectresourcesform=collectresourcesform,
                            upgradebuildingform=upgradebuildingform,
                            required_resources=required_resources)


# Route to display barracks building
@bp.route('/building_barracks/<building_progress_id>', methods=['GET', 'POST'])
@login_required
def building_barracks(building_progress_id):

    building_progress = BuildingProgress.query.filter_by(id=building_progress_id).first()
    game = g.game

    heroes = HeroProgress.query.filter_by(game_id=game.id).all()
    
    return render_template("game/buildings/building_barracks.html",
                            title='Barracks',
                            game=game,
                            building_progress=building_progress,
                            heroes=heroes)



@bp.route('/hero/<hero_progress_id>', methods=['GET','POST'])
@login_required
def hero(hero_progress_id):
    hero_progress = HeroProgress.query.filter_by(id=hero_progress_id).first()
    game = g.game

    return render_template("game/hero.html",
                           title=f"Hero: {hero_progress.hero.hero_name}",
                           hero_progress=hero_progress,
                           game=game)
    
@bp.route('/building_campaign/<building_progress_id>', methods=['GET','POST'])
@login_required
def building_campaign(building_progress_id):
    
    building_progress = BuildingProgress.query.filter_by(id=building_progress_id).first()
    game=g.game
    
    return render_template("game/buildings/building_campaign.html",
                           title="Campaign",
                           game=game,
                           building_progress=building_progress)
    
    
@bp.route('/battle', methods=['GET','POST'])
@login_required
def battle():
    
    game=g.game
    
    return render_template("game/battle.html",
                           title="Campaign",
                           game=game)

app/templates/game/buildings/building_barracks.html
{% extends "game/game_base.html" %}

{% block content2 %}

<div>
    <h2> All Heroes </h2>


    <div class="container mt-3">
        <div class="row">
            {% for hero in heroes %}
            <div class="col-md-4 mb-4">
                <!-- Wrap the card with an <a> tag -->
                


                    <div class="card hero-active">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ hero.hero.hero_name }}</h5>
                            <p class="card-text">{{ hero.hero.hero_description }}</p>
                            <p class="card-text">Level: {{ hero.hero_level }}</p>
                            <a href="{{ url_for('game.hero', hero_progress_id=hero.id)}}" class="card-link">View Hero</a>
                        </div>
                    </div>
            </div>
            {% if loop.index % 2 == 0 %}
        </div><div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>



{% endblock content2 %}

app/templates/game/buildings/building_campaign.html
{% extends "game/game_base.html" %}

{% block content2 %}




{% endblock content2 %}

app/templates/game/buildings/building_inventory.html
{% extends "game/game_base.html" %}

{% block content2 %}



<div>
    <h2>Inventory</h2>
    <p>Here are the items in your inventory:</p>
    <ul>
        {% for inventory in userinventories %}
        <li> {{ inventory.id }} </li>
        <ul>
            {% for item in inventory.inventory_items %}
            <li> {{ item.item.item_name }} - {{ item.item.item_description }} - Quantity = {{ item.quantity }} </li>
            {% endfor %}
        </ul>


        {% endfor %}
    </ul>
</div>



{% endblock content2 %}

app/templates/game/buildings/building_quests.html
{% extends "game/game_base.html" %}

{% block content2 %}



<div class="row">
    <div class="col-md-12"> <!-- Adjusted for full width -->
        <div class="card">
            <div class="card-header bg-primary text-white">Active Quests</div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Quest Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Actions</th> <!-- Column for the form if quest_progress == 100 -->
                        </tr>
                    </thead>
                    <tbody>
                        {% for quest in active_quests %}
                        <tr>
                            <td>{{ quest.quest_quest.quest_name }}</td>
                            <td>{{ quest.quest_quest.quest_description }}</td>
                            <td>
                                {% if quest.quest_progress == 100 %}
                                <form action="" method="post">
                                    {{ completequestform.csrf_token()  }}
                                    {{ completequestform.quest_id(value=quest.id) }}
                                    {{ completequestform.complete_button() }}
                                </form>
                                {% else %}
                                In Progress
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<br>

<div class="col-md-12">
    <div class="card">
        <div class="card-header bg-success text-white">Completed Quests</div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Quest Name</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for quest in completed_quests %}
                    <tr>
                        <td>{{ quest.quest_quest.quest_name }}</td>
                        <td>{{ quest.quest_quest.quest_description }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<br>

<div class="col-md-12">
    <div class="card">
        <div class="card-header bg-secondary text-white">Inactive Quests</div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Quest Name</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for quest in inactive_quests %}
                    <tr>
                        <td>{{ quest.quest_quest.quest_name }}</td>
                        <td>{{ quest.quest_quest.quest_description }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>






{% endblock content2 %}

app/templates/game/buildings/building_resource.html
{% extends "game/game_base.html" %}

{% block content2 %}

<script type="text/javascript">
    var loc = window.location;
    var wsStart = loc.protocol === "https:" ? "wss://" : "ws://";
    var wsUrl = wsStart + loc.host + "/ws/building_resource";
    var buildingSocket = new WebSocket(wsUrl);

    buildingSocket.onopen = function(event) {
        console.log('Building resource WebSocket is open now.');
        // Send a valid building_progress_id
        requestResourceUpdate('{{ building_progress.id }}'); // Replace '3' with a valid ID
    };

    buildingSocket.onmessage = function(event) {
        console.log('Received message from server: ' + event.data);
        var data = JSON.parse(event.data);
        if (data.event === 'resource_update') {
            console.log('Resource update received:', data);

            var accruedCashElement = document.getElementById('accrued_cash');
            var accruedWoodElement = document.getElementById('accrued_wood');
            var accruedStoneElement = document.getElementById('accrued_stone');
            var accruedMetalElement = document.getElementById('accrued_metal');
            
            if (accruedCashElement) accruedCashElement.innerText = data.accrued_cash;
            if (accruedWoodElement) accruedWoodElement.innerText = data.accrued_wood;
            if (accruedStoneElement) accruedStoneElement.innerText = data.accrued_stone;
            if (accruedMetalElement) accruedMetalElement.innerText = data.accrued_metal;

        } else if (data.error) {
            console.error('Error from server:', data.error);
        } else {
            console.log('Unexpected message type:', data.event);
        }
    };

    buildingSocket.onclose = function(event) {
        console.log('Building resource WebSocket is closed now.');
    };

    buildingSocket.onerror = function(error) {
        console.log('Building resource WebSocket error: ' + error);
    };

    function requestResourceUpdate(buildingProgressId) {
        var message = {
            event: 'resource_update',
            building_progress_id: buildingProgressId
        };
        console.log('Sending message to server:', message);
        buildingSocket.send(JSON.stringify(message));
    }
</script>

<div class="building-section">
    <h2>{{ building_progress.building.building_name }} - Level: {{ building_progress.building_level }}</h2>


    <!-- RESOURCE SECTION FOR RESOURCE BUILDING-->
    <div class="resource-info">
        <!-- Farm -->
        <div class="resource-card">
            {% if building_progress.building.id == 3 %}
            <i class="fas fa-dollar-sign"></i> <!-- Example icon usage -->

            <p>Cash per minute: {{ building_progress.cash_per_minute }}</p>
            <p>Accrued Cash: <span id="accrued_cash">0</span></p>
            {% endif %}

            <!-- Lumber Mill -->
            {% if building_progress.building.id == 4 %}
            <p>Wood per minute: {{ building_progress.wood_per_minute }}</p>
            <p>Accrued Wood: <span id="accrued_wood">0</span></p>
            {% endif %}

            <!-- Mine -->
            {% if building_progress.building.id == 5 %}
            <p>Stone per minute: {{ building_progress.stone_per_minute }}</p>
            <p>Accrued Stone: <span id="accrued_stone">0</span></p>
            {% endif %}

            <!-- Forge -->
            {% if building_progress.building.id == 6 %}
            <p>Metal per minute: {{ building_progress.metal_per_minute }}</p>
            <p>Accrued Metal: <span id="accrued_metal">0</span></p>
            {% endif %}

            <!-- Check if any resources to collect before displaying button -->
            {% if buildingservice.check_resources_to_collect() %}
            <div class="collect-button">
                <form action="" method="post">
                    {{ collectresourcesform.hidden_tag() }}
                    <p>{{ collectresourcesform.collect_button() }}</p>
                </form>
            </div>
            {% endif %}

        </div>
    </div>


   
<!-- UPGRADE SECTION FOR RESOURCE BUILDING-->
    <h2>Upgrade:</h2>

    <div class="resource-info">
        <div class="resource-card">

            {% if building_progress.building_level >= building_progress.building.max_building_level %}
            <p>Building Upgraded to Max Level</p>
            {% else %}

            <p>Game Level: {{ game.level }} / {{ required_resources.level }}</p>
            <p>Cash: {{ game.cash }} / {{ required_resources.cash }}</p>

            <!-- Farm -->
            {% if building_progress.building.id == 3 %}
            {% endif %}

            <!-- Lumber Mill -->
            {% if building_progress.building.id == 4 %}
            {% endif %}

            <!-- Mine -->
            {% if building_progress.building.id == 5 %}
            <p>Wood: {{ game.wood }} / {{ required_resources.wood }}</p>
            {% endif %}


            <!-- Forge -->
            {% if building_progress.building.id == 6 %}
            <p>Wood: {{ game.wood }} / {{ required_resources.wood }}</p>
            <p>Stone: {{ game.stone }} / {{ required_resources.stone }}</p>
            {% endif %}

            {% if buildingservice.check_upgrade_requirements() %}
            <form action="" method="post">
                {{ upgradebuildingform.hidden_tag() }}
                <p>{{ upgradebuildingform.upgrade_button() }}</p>
            </form>
            {% else %}
            <p>Requirements not met</p>
            {% endif %}
            {% endif %}


        </div>
    </div>
</div>



{% endblock content2 %}